# Generated by Django 5.2.8 on 2026-06-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Designates whether this user has an active Pro subscription.', verbose_name='Pro plan'),
        ),
    ]
